concord-consortium/flow-server

- static/common/core.js
- static/common/messages.js
- static/flow/diagram-editor.js
- templates/flow-app.html
When saving diagram, perform validation on name and reject if name contains the following illegal chars: '/', '\', '*', '?'
> Diagram name validation

- static/common/core.js
- static/common/messages.js
- static/flow/diagram-editor.js
- templates/flow-app.html
Checks if the diagram is modifed via g_modified when beforeunload event is triggered, generally on browser reload or closing tab/window, but browsers can override this behavior:
https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeunload
> Warning on close when diagram is modifed

- static/common/core.js
- static/common/messages.js
- static/flow/controller-viewer.js
- static/flow/diagram-editor.js
- static/flow/flow-util.js
- static/flow/style.css
- templates/flow-app.html
Basic UI (using bootstrap collapse) to show link to controller status. Currently shows the device count sent from the controller client
> Controller status

- static/flow/plotter.js
Using code from `plotter.html`
Can lead to confusing issue if data initally retrieved is spread across a large time window, smothering newer data that comes in. Might be possible to sample the rate of new data and use it to select a smaller time window so that updates are more obvious
> Live data in plotter

- static/flow/diagram-editor.js
- static/flow/diagram.js
- static/flow/plotter.js
Track history of a block in memory and use for sequence plotter until server history can be merged
> Block history

- static/external/manyplot.js
- static/flow/diagram-editor.js
- static/flow/diagram.js
- static/flow/plotter.js
- static/flow/style.css
- templates/flow-app.html
Showing selector for time frame under plotter. Clicking a time retrieves data set from server and combines with locally stored data. Local data is not mutated so that user can page through different sets of data. Quite fragile, owing to fact that there are two different handlers updating the data (one for the block history, one for the plotter data columns)
> Plotter timeframe

- static/flow/controller-selector.js
- static/flow/controller-viewer.js
- static/flow/diagram-editor.js
- static/flow/flow-app.js
- static/flow/plotter.js
- static/flow/style.css
- templates/flow-app.html
Controller selector and viewer in Vue.js. Removing global variables where possible, leveraging Vue.js templating and reactivity to reduce code
> Vue.js implementation

- static/flow/controller-selector.js
- static/flow/controller-viewer.js
- static/flow/diagram-editor.js
- static/flow/flow-app.js
- static/flow/plotter.js
- static/flow/style.css
- templates/flow-app.html
Reverts manylabs/flow-server#10
> Revert "Vue.js implementation"

- static/flow/diagram-editor.js
> Handle null block values

- static/flow/diagram-editor.js
> Fixed brightness misspelling

- static/external/manyplot.js
- static/flow/diagram.js
- templates/flow-app.html
When plot is put into intervalSelect mode, click and drag across to set interval bounds and mark red in the plotter
> Manyplot data selection

- static/flow/diagram-editor.js
Not tested, having issues with TLS when connecting to local server
> Feature: Added smoothing filter options

- static/flow/diagram-editor.js
Added Simple Moving Average/Exponential Moving Average filters and created new block type to display a number with input from parameters similar to blur/brightness.
> Feature: Added SMA/EMA filters, created new block type

- static/common/messages.js
- static/flow/controller-viewer.js
- templates/flow-app.html
Please review. 
[#151489580]
See PT story https://www.pivotaltracker.com/story/show/151489580
> Fix UI sending messages to wrong controllers.

- static/flow/controller-viewer.js
- templates/flow-app.html
Needed to add some updates to this fix.
Call `sendSubscriptions()` only when websocket has been inited.
Add controller name to info in diagram view.
[#151489580]
> Call sendSubscriptions() only when websocket has been inited.

- static/flow/controller-viewer.js
- static/flow/diagram-editor.js
- templates/flow-app.html
This displays the diagram name as part of the diagram editor view and also refactors the updating of the editor view to reflect that it is updating more than just the interval.
> Add diagram name

- ext.py
- static/common/messages.js
- static/flow/controller-selector.js
- static/flow/controller-viewer.js
- static/flow/diagram-editor.js
- static/flow/flow-util.js
- templates/flow-app.html
> 151489214 fix status

- ext.py
- static/common/messages.js
- static/flow/admin-view.js
- static/flow/controller-selector.js
- static/flow/controller-viewer.js
- static/flow/flow-app.js
- static/flow/flow-util.js
- static/flow/style.css
- templates/flow-app.html
Please review. Added admin dashboard.
> 152092418 admin dashboard

- static/flow/controller-viewer.js
- static/flow/diagram-editor.js
- static/flow/flow-util.js
- templates/flow-app.html
> 152091864 prevent modification when recording

- ext.py
- flow-admin.py
- static/flow/admin-view.js
- static/flow/flow-app.js
- static/flow/flow-util.js
- static/flow/style.css
- static/flow/util/message-executor.js
- static/flow/views/admin-view.js
- static/flow/views/base-view.js
- static/flow/views/dataset-icon.js
- static/flow/views/landing-page-data-set-view.js
- static/flow/views/landing-page-my-programs-view.js
- static/flow/views/landing-page-view.js
- static/flow/views/my-data-panel.js
- static/flow/views/pi-selector-panel.js
- static/flow/views/pi-selector.js
- static/flow/views/program-editor-file-manager.js
- static/flow/views/program-editor-view.js
- static/flow/views/program-icon.js
- templates/flow-app.html
Please review. This is a lot of changes so you might have comments.
This is a work in progress but it's going to be a problem with conflicts as you make other changes if it doesn't get merged even though it is still not feature complete.
This is missing diagram edit UI and plotter. But the new features are hidden unless user enables them with an http parameter. Once they are complete I'll remove the old code.
> 152357358 my saved programs

- ext.py
- static/flow/views/admin-view.js
> Add user admin to admin UI.

- static/external/manyplot.js
- static/flow/style.css
- static/flow/views/data-set-view.js
- static/flow/views/landing-page-data-set-view.js
- static/flow/views/pi-selector-panel.js
- static/flow/views/program-editor-file-manager.js
- static/flow/views/program-editor-panel.js
- static/flow/views/program-editor-view.js
- update dataview plot dynamically when recording
- improve highlight display in data plot
- better messaging on button when waiting for message response
- fix bug that caused incorrect run program button state
- add rules to ensure valid filenames
- ensure relay block shows on/off
> post classroom trial changes to improve usability

- ext.py
- static/flow/style.css
- static/flow/views/data-set-view.js
- static/flow/views/landing-page-data-set-view.js
- static/flow/views/landing-page-my-programs-view.js
- static/flow/views/pi-selector-panel.js
- static/flow/views/program-editor-file-manager.js
- static/flow/views/program-editor-panel.js
- static/flow/views/program-editor-view.js
- static/flow/views/recording-status-panel.js
Modify file structure so that both the datasets and the program use the folder -> content, metadata structure.  Create archived and displayedName parameters in metadata so datasets and programs have an internal name, a displayed name, and can be marked as archived to indicate that content is hidden from user but not deleted internally.
> File structure changes

- static/flow/filters.js
The correct computation of EMA:
k = 2/(n+1) or  alpha = 2/(boxsize + 1)
ema = current*k + emaPrev * (1-k)
represented in our code:
avg = newValue*k + block.lastAverage * (1-alpha)
> corrections to EMA calculcation on flow-server

- static/flow/views/data-set-view.js
[#158746013]
Ensure dataset displays the program name by checking its metadata for both the name and displayedName - allows us to support current and old versions of dataset metadata.
> ensure dataset displays program name used to create

- static/flow/views/landing-page-data-set-view.js
- static/flow/views/pi-selector-panel.js
[#158962987]
Add callback function to stopRecording so we can refresh/update any view that calls function.
> add callback function to stopRecording

- README.md
> update flow-server readme

- static/external/manyplot.js
> Fix placement of highlight point on dataview

- static/flow/style.css
- static/flow/views/landing-page-data-set-view.js
- static/flow/views/landing-page-my-programs-view.js
- static/flow/views/landing-page-view.js
refactor landing page code to do the following:
-unify css naming conventions
-remove white space
-unify use of quotes
-unify use of spacing
-unify use of brackets around if/else
[#159321743]
> refactor code in landing page

- static/flow/views/landing-page-data-set-view.js
- static/flow/views/landing-page-my-programs-view.js
The only meat here is adding an error message when we do not get a program list in lines 63 and 68 of landing-page-my-programs-view.js.  The rest is just refactoring to clean up some of the surrounding code areas.  There were a couple functions that basically did the same thing so I merged them together.
[#159319576]
> add error message when we fail to load programs

- static/flow/diagram-editor.js
- static/flow/style.css
- static/flow/views/program-editor-panel.js
the meat is in program-editor-panel.js line 345 - this is where we add a div with the 'sec" label into the data storage block.
the other changes in program-editor-panel and the changes in diagram-editor and style.css are mainly just refactoring (spacing and css class naming conventions)
[#159319736]
> add seconds label to data storage block

- static/flow/style.css
- static/flow/views/program-editor-panel.js
- static/flow/views/program-editor-view.js
This is the first pass at adding autosave and undo to dataflow.  All program changes in the editor (move block, add block, remove block, change name, etc.) now invoke an autosave function.  An array of program states is stored so that the user can also use ctrl + z to undo changes as they are working.
> 158990664 autosave

- static/flow/views/program-editor-block-palette.js
Use existing jQueryUI to add tooltips via element title.
[#159285984]
> add tooltips to menu items

- static/flow/views/admin-view.js
- static/flow/views/base-view.js
- static/flow/views/data-set-view.js
- static/flow/views/fullscreen-widget.js
- static/flow/views/landing-page-data-set-view.js
- static/flow/views/landing-page-my-programs-view.js
- static/flow/views/landing-page-view.js
- static/flow/views/login-page-view.js
- static/flow/views/pi-selector-panel.js
- static/flow/views/program-editor-block-palette.js
- static/flow/views/program-editor-panel.js
- static/flow/views/program-editor-view.js
> unify jquery usage

- static/flow/ble-app.js
- static/flow/codap-bridge.js
- static/flow/diagram.js
- static/flow/filters.js
- static/flow/flow-app.js
- static/flow/flow-util.js
- static/flow/plotter.js
- static/flow/views/admin-view.js
- static/flow/views/data-set-view.js
- static/flow/views/landing-page-data-set-view.js
- static/flow/views/landing-page-my-programs-view.js
- static/flow/views/landing-page-view.js
- static/flow/views/pi-selector-panel.js
- static/flow/views/program-editor-block-palette.js
- static/flow/views/program-editor-panel.js
- static/flow/views/program-editor-view.js
> refactor whitespace, brackets, and if/else/for style

- static/flow/views/data-set-view.js
- static/flow/views/landing-page-view.js
make sure we stop requesting live updates of a currently-recording-dataset if we load a new dataset or close the dataset view.
> 159499597 live dataset continues requesting

- static/flow/views/pi-selector-panel.js
add a 30 second timeout when requesting that a pi starts or stops a program.  If timeout fires, clear message handler and display message to user indicating that pi is not responding.
> 159319561 add startstop timeout

- ext.py
Sending the init message on a newly connected socket does not work on a Pi that is started cold.
This change adds a 1 second delay after the connect before the init message is sent.
> Add delay before sending firebase init on connect

- static/flow/views/program-editor-panel.js
Added event sink to pin mouse down handler to prevent browser drag behavior.
> Fixed "ghost" drags [#156943669]

- static/flow/views/program-editor-panel.js
Adds special case for empty string which parseFloat() returns as a NaN.
> Fix delete of interval in the data storage block [#159178602]

- static/flow/flow-app.js
Add code back in to show fullscreen widget
[#159281049]
> fix fullscreen button

- flow-server release process.md
> add document detailing how to make release

- static/flow/views/pi-selector-panel.js
Addresses issue https://www.pivotaltracker.com/story/show/161564058
> Reduce Firebase timeout to 15s
