concord-consortium/flow-server

static/flow/controller-viewer.js
Using bootstrap's btn-dropdown functionality for the menu:
http://getbootstrap.com/components/#btn-dropdowns
Added a new method to update the diagramSpecs (to delete a spec) but I think ultimately might want to consider having a listener be the only one to modify the client representation of diagrams to avoid state nastiness. Instead of removing a diagram on the client side, then, instead you'd want to signal deletion to the controller, the controller deletes it and then sends a `list_diagrams` with the new list, which has omitted the deleted diagram
=> Dropdown menu for diagram rename/delete

static/flow/diagram-editor.js
For some reason, the canvas element of the plot block does not propagate events to the diagram editor element. So, when creating this element, bind the mouse events manually. There might be a more elegant solution possible so I'm reading up a little on event propagation for canvas elements
=> Draggable plot blocks

static/flow/diagram-editor.js
Set a flag to track when there has been a message received from the controller. If 5 seconds pass without a message, show a prompt to go back to the controller select view.
=> Prompt if not connected to controller

.editorconfig, static/flow/codap-bridge.js, static/flow/controller-selector.js, static/flow/controller-viewer.js, static/flow/diagram-editor.js, static/flow/plotter.js, templates/flow-app.html
The .editorconfig file ensures that tab/space conventions are automatically set in any editors that support it (see http://editorconfig.org/)
For logging:
- two new functions were added to CodapTest: log() and logTopic()
- logTopic() calls were inserted to support triggers for external Getting Started data interactive
=> Added .editorconfig and logging to CODAP

static/flow/diagram-editor.js
This was causing the "Getting Started" data interactive to block.
=> Added missing Dataflow/ViewRecordedData logTopic call

ext.py
I haven't tested this, but I think it will fix a problem we are having when I started using a postgres database.
We are seeing the error below when saving programs/diagrams.  I believe this is because `request.values.get('content')` returns a unicode object.  And the ORM is trying to convert that unicode object to a binary object. I'd guess the postgres adapter is more strict than the sqlite adapter.
```
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
return self.wsgi_app(environ, start_response)
File "/usr/local/lib/python2.7/dist-packages/flask_sockets.py", line 48, in __call__
return self.wsgi_app(environ, start_response)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
response = …
```
=> try to fix error with postgres db and unicode

ext.py
Some existing resources have no content, so they were giving this error:
`AttributeError: 'NoneType' object has no attribute 'decode'`
=> handle null resource content

static/flow/views/pi-selector-panel.js, static/flow/views/program-editor-panel.js, static/flow/views/program-editor-view.js
pi-selector-panel.js was due for clean-up.  Clean-up might have been better placed in a tech-debt branch, but naming conventions and excess code were throwing me off as I hunted for pi connection bugs so I did some housekeeping.  I removed whitespace, refactored code, and removed obsolete comments.  
More important are the changes related to problems with the pi connection drop down menu and pi connection troubles.  Changes in simulateRunProgramState() prevent duplicate entry of Pi name in dropdown menu.  Restructure of loadPiList() and addPisToMenu() fix issues caused when we tried to reload the Pi list on deviceDropDownMenu focusin event - we were losing the reference to the currently selected Pi.  We need to keep the list up to date, but can be less aggressive about resetting variables …
=> Pi connection fixes

static/flow/views/program-editor-panel.js
[#158230075]
usability change: easier for the user to understand what the data storage block does by using more human readable default dataset name.  No longer base name on current date/time.  Instead use format = "my program dataset" where "my program" is the current displayed program name.  Keep old date/time code around in function in case we need it later on.
=> base default dataset name on program name instead of date/timestamp

static/flow/views/data-set-view.js
[#158847341]
Old model searched blocks in diagram to determine which blocks were stored as sequences.  New model allows user to connect any block to data storage block so sequence is saved.  To ensure correct attributes are sent to CODAP, get attribute info from the actual loaded dataPair which will be exported to CODAP (rather than parsing it out of program).
=> get correct attributes when exporting to CODAP

static/flow/views/program-editor-panel.js
[#158746018]
Legacy programs (programSpec.name == null) need to have an internal program name created when they are opened to ensure that they can be saved using the modern internal file structure.
=> create new internal program name when opening old, legacy programs

static/flow/views/landing-page-data-set-view.js, static/flow/views/pi-selector-panel.js, static/flow/views/program-editor-panel.js, static/flow/views/program-editor-view.js
Handle fileIO workflow case where user loads and resaves a program stored in a dataset's metadata.  In this case, the program does not have an internal file name and is not previously stored on the server (only exists as a representation within the dataset metadata).  Ensure that we define program spec correctly and give program an internal date/time name in this case.
=> 158484929 saved program wrong internal

static/flow/views/landing-page-data-set-view.js
[#158991159]
Another issue where there is confusion between the displayedName and the old file name.  Be sure to support legacy and modern datasets.
=> Display correct dataset name when prompting user to delete

static/flow/views/pi-selector-panel.js
If caller provides device information when stopping program, always use it.  Otherwise, call back on the last used values.  Allows us to stop program from the editor stop button or from some external caller/program space (like the activity feed stop button).
[#159178473]
=> use proper controller info when stopping program

static/flow/views/data-set-view.js
We shouldn't hit this case in ideal situations, but we have some legacy datasets that were created in testing that throw exceptions.  Make sure we ignore bad data and do not have exceptions or errors in the console window.
[#158737293]
=> exit load sequence if contents are null

ext.py, static/flow/flow-app.js, static/flow/images/fullscreen-exit.svg, static/flow/images/fullscreen.svg, static/flow/style.css, static/flow/views/fullscreen-widget.js, templates/flow-app.html
Fullscreen is optionally shown via a URL parameter (hence the changes in ext.py, flow-app.js, and flow-app.html).  You'll also see some whitespace clean up in these modules which makes up a bulk of the diff.  SVG files and fullscreen implementation in fullscreen-widget was taken from existing implementation in SEPA app as per Sam's recommendation (and trying to ensure unified look of tools in CC apps).
=> 159281049 add full screen button dataflow

static/flow/views/pi-selector-panel.js
Request to eliminate rule that a pi *must* have a sensor of type n to run a program with a type n sensor block (so, for example, previously if a program included a light sensor, the pi had to have a light sensor attached to run).  This will eventually tie to the larger discussion of how we display data since this can, in theory, allow a user to collect a data sequence of null values (adds block that doesn't have an analogous physical sensor, attaches block to data storage block, runs program).  However, this can be addressed in a future dataview specific story.
=> program no longer requires a live sensor to have a sensor block

static/flow/views/program-editor-panel.js
Reset lastChangeMoveBlock after undo so that subsequent moves are recorded an can then be undone.  Fixes issue where user would move block, undo, move block again, attempt undo, but undo would not do anything.
[#159490111]
=> allow user to move block, undo, and then undo future moves

static/flow/views/landing-page-data-set-view.js, static/flow/views/pi-selector-panel.js, static/flow/views/program-editor-view.js
When an activity feed block is created that contains a running program, start a timer that polls the server to obtain pi statuses.  If a pi status has changed, update the UI to reflect this change (e.g., if UI says Pi is offline, but server reports that pi is now back online, update UI so user knows state of Pi).  When we leave the landing page/activity feed, stop polling the server for pi status.
=> 159319537 activity feed update realtime

static/flow/views/program-editor-panel.js
make deep copy of program spec to avoid variable clashing, move autosave to more efficient location.  Previous copy of spec was shallow so internal objects were passed by reference to storage array.  Inadequate for our purposes.  Might be a better way than current method:
var currentProgramCopy = JSON.parse(JSON.stringify(diagramToSpec(_this.m_diagram)));
But for now this method should do the job.
[#159515335]
=> fix autosave input field issues

static/flow/views/program-editor-panel.js
Add calls to update blocks after ctrl+z undo and after program load.  Math blocks (such as plus, minus, etc.) were not updating when they had value inputs.  Instead showed invalid string "..."
[#159514952]
=> update blocks after undo and load

static/flow/flow-util.js, static/flow/views/program-editor-panel.js
Reverted recent code change that appended instead of replaced text while generating filenames causing very long invalid filenames.
Also added check in filename parser for the tooltips to return an error string if it can't be parsed instead of returning NaN in the string.
=> Fixed generation of filenames [#159953929]

static/external/manyplot.js, static/flow/views/data-set-view.js
This should ensure that plots always render in alphabetical order, regardless of the order of the plot pairs. Manyplot can be initialized with multiple data sequences per set and can choose to display as individual graphs or as stacked graphs on the same plot. Since we don't use the multiple data sequences on the same graph approach at the moment, the requirement is for consistency in rendering the datasets when re-opening the results. I've used a very simple alphabetic sort for the name of the sensor for this.
Added configuration option to disable this feature if required. This should also ensure consistent rendering whenever the plot data is updated with new sequences.
=> Sort rendering of graphs in the dataset view

static/external/manyplot.js, static/flow/style.css, static/flow/views/data-set-view.js, templates/flow-app.html
When a dataset is being viewed, interval selection would fail if any sequence in the set was empty. This fix should still allow interval selection for valid data sequences with pairs of data, and hand only those sequences to CODAP for analysis.
=> Fix CODAP export bug

static/flow/views/program-editor-panel.js
Allow support of multiple sensors of same type.  When generating a unique name for a sensor block, ensure that this name matches what is passed from the flow-client (which identifies and assigns names to sensors).  Also ensure that we properly update the nameHash object which maps block name passed from flow client to the actual flow blocks.  This object must be correctly maintained when loading a program, renaming a block, deleting a block, or undoing changes.
Note 1: There is some minor refactoring which might make the comparison a little tricky.  I'm trying to knock some linting out each time I work in an area.  In the future, I'll add these to a separate branch/PR for clarity.
Note 2: present model assume that there is a direct match between sensor block and timer names in the …
=> 160838943 multiple sensors same type

static/flow/views/pi-selector-panel.js, static/flow/views/program-editor-view.js
Prevent sensor values from appearing in blocks when no Pi is selected ("none" in the Pi selection list in the topbar).  Firebase connection was only previously stopped when user explicitly selected "none" from the Pi selection list.  However, Pi selection is also set to "none" when loading a new program.  Changes stop Firebase sensor updates from controller (Pi) when we load a new program to ensure that incorrect values from previously selected Pi are not shown in flow blocks.
- add `firebaseControllerReset()` function which we call when we set the Pi selection to "none".  This can be done manually by the user but also happens when a new program is loaded or we try to reselect a Pi that is no longer available (and hence set "none" for Pi selected)
- consolidate action when "none" is …
=> 160738755 sensor values show when none selected

static/flow/diagram.js, static/flow/views/program-editor-panel.js
Ensure sensor and timer values are null when loading a program.  At present we are forcing sensor values to null when saving a program.  However, there are some older style programs that were saved with sensor values in the program spec (value should always be null to prevent displaying erroneous sensor value). Expand protection to handle when opening old programs.
=> Ensure sensor and timer values are null when loading a program

ext.py
Change delay from 1 sec to 6 sec so Pi Zeros have time to boot up before we tell them to connect to Firebase.  6 seconds was the requested time from Lisa based on her tests with Pi Zeros (I don't have one for testing so I'm relying on her to provide an acceptable delay time).
=> change firebase init delay
